spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: service-user
  registry:
    address: zookeeper://192.168.184.188:2181
  consumer:
    check: false
  protocol:
    port: -1
